### ISSUE TITLE
Kayla

### ISSUE THREAD

**Issue by KnifuWaifu** [ProjectYamada/Yamada#1]
There needs to be more Kayla-ness

**Comment by auguwu** [comment]
despacito kayla when

**Comment by KnifuWaifu** [comment]
tonight

**Comment by Sanae6** [comment]
kaylaness will be injected when translations are allowed

**Comment by kanielyaniel** [comment]
This is so sad

**Comment by Sanae6** [comment]
Can we Kaylafy the bot

**Comment by kanielyaniel** [comment]
yeah we should

**Comment by Sanae6** [comment]
i remember saying we will

**Comment by kanielyaniel** [comment]
at some point bill changed it from "all about Kayla" to "all about Yamada"

**Comment by Sanae6** [comment]
right around the time i left he did some commits and changed that yeah
